version: "3"

services:
  app:

    build:
      context: .
    container_name: pyapicore
    image: pyapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
